package edu.nku.CSC440.stagbar.ui.menu;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import edu.nku.CSC440.stagbar.Application;
import edu.nku.CSC440.stagbar.ui.common.uiHacks;
import edu.nku.CSC440.stagbar.ui.report.ReportDateSelectorUI;

import javax.swing.*;
import java.awt.*;

public class MainMenuUI {
	private JButton alcoholButton;
	private JPanel contentPane;
	private JButton dataEntryButton;
	private JButton manageUsersButton;
	private JButton mixedDrinksButton;
	private JButton reportsButton;

	public MainMenuUI() {
		contentPane.setName("Main Menu");

		alcoholButton.addActionListener(e -> onAlcohol());
		dataEntryButton.addActionListener(e -> onDataEntry());
		manageUsersButton.addActionListener(e -> onManageUsers());
		mixedDrinksButton.addActionListener(e -> onMixedDrinks());
		reportsButton.addActionListener(e -> onReports());

		if(!Application.getInstance().getUser().isAdmin()) { disableAdminOnlyButtons(); }
	}

	/** @noinspection ALL */
	public JComponent $$$getRootComponent$$$() { return contentPane; }

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		contentPane = new JPanel();
		contentPane.setLayout(new GridLayoutManager(5, 1, new Insets(10, 10, 10, 10), -1, -1));
		contentPane.setPreferredSize(new Dimension(250, 189));
		mixedDrinksButton = new JButton();
		mixedDrinksButton.setText("Mixed Drinks");
		contentPane.add(mixedDrinksButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		reportsButton = new JButton();
		reportsButton.setText("Reports");
		contentPane.add(reportsButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		manageUsersButton = new JButton();
		manageUsersButton.setText("User Management");
		contentPane.add(manageUsersButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		alcoholButton = new JButton();
		alcoholButton.setText("Alcohol");
		contentPane.add(alcoholButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		dataEntryButton = new JButton();
		dataEntryButton.setText("Data Entry");
		contentPane.add(dataEntryButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	private void disableAdminOnlyButtons() {
		alcoholButton.setEnabled(false);
		mixedDrinksButton.setEnabled(false);
		dataEntryButton.setEnabled(false);
	}

	public JPanel getContentPane() {
		return contentPane;
	}

	private void onAlcohol() {
		AlcoholMenuUI alcoholMenuUI = new AlcoholMenuUI();
		uiHacks.goToPanel(contentPane, alcoholMenuUI.getContentPane());
	}

	private void onDataEntry() {
		DataEntryMenuUI dataEntryMenuUI = new DataEntryMenuUI();
		uiHacks.goToPanel(contentPane, dataEntryMenuUI.getContentPane());
	}

	private void onManageUsers() {
		UserManagementMenuUI manageUsers = new UserManagementMenuUI();
		uiHacks.goToPanel(contentPane, manageUsers.getContentPane());
	}

	private void onMixedDrinks() {
		MixedDrinkMenuUI mixedDrinkMenuUI = new MixedDrinkMenuUI();
		uiHacks.goToPanel(contentPane, mixedDrinkMenuUI.getContentPane());
	}

	private void onReports() {
		ReportDateSelectorUI reportDateSelectorUI = new ReportDateSelectorUI();
		uiHacks.goToPanel(contentPane, reportDateSelectorUI.getContentPane());
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

}
