package edu.nku.CSC440.stagbar.ui.menu;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import edu.nku.CSC440.stagbar.Application;
import edu.nku.CSC440.stagbar.ui.common.uiHacks;
import edu.nku.CSC440.stagbar.ui.user.ChangePasswordUI;
import edu.nku.CSC440.stagbar.ui.user.CreateUserUI;
import edu.nku.CSC440.stagbar.ui.user.DeleteUserUI;

import javax.swing.*;
import java.awt.*;

public class UserManagementMenuUI {
	private JButton changePasswordButton;
	private JPanel contentPane;
	private JButton createUserButton;
	private JButton deleteUserButton;
	private JButton editUserPermissionsButton;
	private JButton goBackButton;

	public UserManagementMenuUI() {
		contentPane.setName("Manage Users");

		changePasswordButton.addActionListener(e -> onChangePassword());
		createUserButton.addActionListener(e -> onCreateUser());
		deleteUserButton.addActionListener(e -> onDeleteUser());
		editUserPermissionsButton.addActionListener(e -> onEditPermissionsUser());
		goBackButton.addActionListener(e -> onGoBack());

		if(!Application.getInstance().getUser().isAdmin()) { disableAdminOnlyButtons(); }
	}

	/** @noinspection ALL */
	public JComponent $$$getRootComponent$$$() { return contentPane; }

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		contentPane = new JPanel();
		contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(10, 10, 10, 10), -1, -1));
		contentPane.setPreferredSize(new Dimension(250, 189));
		changePasswordButton = new JButton();
		changePasswordButton.setText("Change Password");
		contentPane.add(changePasswordButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		goBackButton = new JButton();
		goBackButton.setText("Go Back");
		contentPane.add(goBackButton, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTH, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		createUserButton = new JButton();
		createUserButton.setText("Create User");
		contentPane.add(createUserButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		editUserPermissionsButton = new JButton();
		editUserPermissionsButton.setText("Edit User Permissions");
		contentPane.add(editUserPermissionsButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		deleteUserButton = new JButton();
		deleteUserButton.setText("Delete User");
		contentPane.add(deleteUserButton, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	private void disableAdminOnlyButtons() {
		createUserButton.setEnabled(false);
		deleteUserButton.setEnabled(false);
		editUserPermissionsButton.setEnabled(false);
	}

	public JPanel getContentPane() {
		return contentPane;
	}

	private void onChangePassword() {
		ChangePasswordUI changePasswordUI = new ChangePasswordUI();
		uiHacks.goToPanel(contentPane, changePasswordUI.getContentPane());
	}

	private void onCreateUser() {
		CreateUserUI createUserUI = new CreateUserUI();
		uiHacks.goToPanel(contentPane, createUserUI.getContentPane());
	}

	private void onDeleteUser() {
		DeleteUserUI deleteUserUI = new DeleteUserUI();
		uiHacks.goToPanel(contentPane, deleteUserUI.getContentPane());
	}

	private void onEditPermissionsUser() {
		//TODO: Navigate to edit permissions
	}

	private void onGoBack() {
		uiHacks.killMeThenGoToLastPage(contentPane);
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

}
