package edu.nku.CSC440.stagbar.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import edu.nku.CSC440.stagbar.Application;

import javax.swing.*;
import java.awt.*;

public class MainMenuUI {
	private JButton alcoholButton;
	private JPanel contentPane;
	private JButton dataEntryButton;
	private JButton deliveriesButton;
	private JButton inventoryButton;
	private JButton manageUsersButton;
	private JButton mixedDrinksButton;
	private JButton newAlcoholButton;
	private JButton reportsButton;
	private JButton retireAlcoholButton;
	private JButton salesButton;

	public MainMenuUI() {
		contentPane.setName("Main Menu");

		manageUsersButton.addActionListener(e -> onManageUsers());
		mixedDrinksButton.addActionListener(e -> onMixedDrinks());
		reportsButton.addActionListener(e -> onReports());

		if(!Application.getInstance().getUser().isAdmin()) { disableAdminOnlyButtons(); }
	}

	/** @noinspection ALL */
	public JComponent $$$getRootComponent$$$() { return contentPane; }

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		contentPane = new JPanel();
		contentPane.setLayout(new GridLayoutManager(5, 1, new Insets(10, 10, 10, 10), -1, -1));
		mixedDrinksButton = new JButton();
		mixedDrinksButton.setText("Mixed Drinks");
		contentPane.add(mixedDrinksButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		reportsButton = new JButton();
		reportsButton.setText("Reports");
		contentPane.add(reportsButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		manageUsersButton = new JButton();
		manageUsersButton.setText("User Management");
		contentPane.add(manageUsersButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		alcoholButton = new JButton();
		alcoholButton.setText("Alcohol");
		contentPane.add(alcoholButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		dataEntryButton = new JButton();
		dataEntryButton.setText("Data Entry");
		contentPane.add(dataEntryButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	private void disableAdminOnlyButtons() {
		newAlcoholButton.setEnabled(false);
		inventoryButton.setEnabled(false);
		salesButton.setEnabled(false);
		retireAlcoholButton.setEnabled(false);
		deliveriesButton.setEnabled(false);
		mixedDrinksButton.setEnabled(false);
	}

	public JPanel getContentPane() {
		return contentPane;
	}

	private void onManageUsers() {
		UserAccountManagementUI manageUsers = new UserAccountManagementUI();
		uiHacks.goToPanel(contentPane, manageUsers.getContentPane());
	}

	private void onMixedDrinks() {
		MixedDrinkMenuUI mixedDrinkMenuUI = new MixedDrinkMenuUI();
		uiHacks.goToPanel(contentPane, mixedDrinkMenuUI.getContentPane());
	}

	private void onReports() {
		//TODO: Navigate to Reports panel
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

}
