package edu.nku.CSC440.stagbar.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import edu.nku.CSC440.stagbar.Application;

import javax.swing.*;
import java.awt.*;

public class MainMenuUI {
	private JPanel contentPane;
	private JButton deliveriesButton;
	private JButton inventoryButton;
	private JButton manageUsersButton;
	private JButton mixedDrinksButton;
	private JButton newAlcoholButton;
	private JButton reportsButton;
	private JButton retireAlcoholButton;
	private JButton salesButton;

	public MainMenuUI() {

		contentPane.setName("Main Menu");

		inventoryButton.addActionListener(e -> onInventory());
		manageUsersButton.addActionListener(e -> onManageUsers());
		mixedDrinksButton.addActionListener(e -> onMixedDrinks());
		newAlcoholButton.addActionListener(e -> onNewAlcohol());
		reportsButton.addActionListener(e -> onReports());
		retireAlcoholButton.addActionListener(e -> onRetireAlcohol());
		salesButton.addActionListener(e -> onSales());
		deliveriesButton.addActionListener(e -> onDeliveries());

		if(!Application.getInstance().getUser().isAdmin()) { disableAdminOnlyButtons(); }
	}

	/** @noinspection ALL */
	public JComponent $$$getRootComponent$$$() { return contentPane; }

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		contentPane = new JPanel();
		contentPane.setLayout(new GridLayoutManager(3, 4, new Insets(10, 10, 10, 10), -1, -1));
		newAlcoholButton = new JButton();
		newAlcoholButton.setText("New Alcohol");
		contentPane.add(newAlcoholButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		inventoryButton = new JButton();
		inventoryButton.setText("Inventory");
		contentPane.add(inventoryButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		salesButton = new JButton();
		salesButton.setText("Sales");
		contentPane.add(salesButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		mixedDrinksButton = new JButton();
		mixedDrinksButton.setText("Mixed Drinks");
		contentPane.add(mixedDrinksButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
		retireAlcoholButton = new JButton();
		retireAlcoholButton.setText("Retire Alcohol");
		contentPane.add(retireAlcoholButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		reportsButton = new JButton();
		reportsButton.setText("Reports");
		contentPane.add(reportsButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		deliveriesButton = new JButton();
		deliveriesButton.setText("Deliveries");
		contentPane.add(deliveriesButton, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		manageUsersButton = new JButton();
		manageUsersButton.setText("Manage Users");
		contentPane.add(manageUsersButton, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	private void disableAdminOnlyButtons() {
		newAlcoholButton.setEnabled(false);
		inventoryButton.setEnabled(false);
		salesButton.setEnabled(false);
		retireAlcoholButton.setEnabled(false);
		manageUsersButton.setEnabled(false);
	}

	public JPanel getContentPane() {
		return contentPane;
	}

	private void onDeliveries() {
		DeliveryUI deliveryUI = new DeliveryUI();
		uiHacks.goToPanel(contentPane, deliveryUI.getContentPane());
	}

	private void onInventory() {
		InventoryUI inventoryUI = new InventoryUI();
		uiHacks.goToPanel(contentPane, inventoryUI.getContentPane());
	}

	private void onManageUsers() {
		UserAccountManagementUI manageUsers = new UserAccountManagementUI();
		uiHacks.goToPanel(contentPane, manageUsers.getContentPane());
	}

	private void onMixedDrinks() {
		MixedDrinkMenuUI mixedDrinkMenuUI = new MixedDrinkMenuUI();
		uiHacks.goToPanel(contentPane, mixedDrinkMenuUI.getContentPane());
	}

	private void onNewAlcohol() {
		NewAlcoholUI newAlcoholUI = new NewAlcoholUI();
		uiHacks.goToPanel(contentPane, newAlcoholUI.getContentPane());
	}

	private void onReports() {
		//TODO: Navigate to Reports panel
	}

	private void onRetireAlcohol() {
		//TODO: Naviagte to retire beverages panel
	}

	private void onSales() {
		SalesUI salesUI = new SalesUI();
		uiHacks.goToPanel(contentPane, salesUI.getContentPane());
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

}
