package edu.nku.CSC440.stagbar.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class UserAccountManagementUI {
	private JPanel contentPane;
	private JButton createUserButton;
	private JButton deleteUserButton;
	private JButton editUserPermissionsButton;

	public UserAccountManagementUI() {
		contentPane.setName("Manage Users");

		createUserButton.addActionListener(e -> onCreateUser());
		deleteUserButton.addActionListener(e -> onDeleteUser());
		editUserPermissionsButton.addActionListener(e -> onEditPermissionsUser());
	}

	/** @noinspection ALL */
	public JComponent $$$getRootComponent$$$() { return contentPane; }

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		contentPane = new JPanel();
		contentPane.setLayout(new GridLayoutManager(1, 3, new Insets(10, 10, 10, 10), -1, -1));
		createUserButton = new JButton();
		createUserButton.setText("Create User");
		contentPane.add(createUserButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		deleteUserButton = new JButton();
		deleteUserButton.setText("Delete User");
		contentPane.add(deleteUserButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		editUserPermissionsButton = new JButton();
		editUserPermissionsButton.setText("Edit User Permissions");
		contentPane.add(editUserPermissionsButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	public JPanel getContentPane() {
		return contentPane;
	}

	private void onCreateUser() {
		CreateUserUI createUserUI = new CreateUserUI();
		uiHacks.goToPanel(contentPane, createUserUI.getContentPane());
	}

	private void onDeleteUser() {

	}

	private void onEditPermissionsUser() {

	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}


}
